spring.application.name=spring-batch





spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}
spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

#disabled job run at startup
spring.batch.job.enabled=false